### ISSUE TITLE
Upgrade the current UI to the Branding Guidelines

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#819]
## Description
As a Developer,
I need to upgrade the UI/UX of VMS,
so that I can satisfy the branding guidelines.

### Update [Required]
- [ ] Navbar updates similar to [AnitaB.org](https://anitab.org/), hover on blue and white with underlines.
- [ ] Headers change to Aubergine (#8D2165).
- [ ] All links are the Caribbean Blue (#54BCEB) and on hover Navy (#005C88).
- [ ] Any confirm/create buttons to Teal (#47BCA0) with on hover (#288F79).
- [ ] Any neutral/view/manage buttons to Caribbean (#54BCEB) with on hover (#3F8CAB).
- [ ] Any cancel/delete buttons to Scarlet (#EF4135) with on hover (#A72D25).
- [ ] LOGIN button to Teal (#47BCA0) with on hover (#288F79).
- [ ] SIGN UP button to Aubergine (#8D2165) with on hover (#690344).

--- Need a Grey Button (only button with black text)
--- Need a Dark Blue Button

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation 
15 hours

**Comment by anjali-dhanuka** [comment]
Hi @abhishekarya286 @kamsuri @nida PLease review the issue.

**Comment by ExactlyMay** [comment]
@anjali-dhanuka I'm going to edit this issue to include a little more than the navbar.

**Comment by anjali-dhanuka** [comment]
@ExactlyMay I was planning to create separate issues for each page.

**Comment by anjali-dhanuka** [comment]
and since nav bar is the same for all the pages, I created this one first.

**Comment by ExactlyMay** [comment]
@anjali-dhanuka Separate issues may be busy. This one hits all the buttons, links, headers, and navbar needs.

I thought CSS changes were all in a central place? That's why I merged it into one issue.

**Comment by anjali-dhanuka** [comment]
closes #839 #847 #841
